"""Type stubs for st_clickhouse."""

from __future__ import annotations

import asyncio
from typing import Any, Callable, Dict, List, Optional, AsyncIterator, Iterator, Tuple

from st_clickhouse._native import (
    _Block,
    _Column,
    _RowIterator,
    _QueryStream,
    blocks_to_dicts,
    dicts_to_block,
)

Block = _Block
Column = _Column

__version__: str


class ClickHouseError(Exception): ...
class ProtocolError(ClickHouseError): ...
class ConnectionError(ClickHouseError): ...
class AuthenticationError(ClickHouseError): ...
class QueryError(ClickHouseError): ...
class TimeoutError(ClickHouseError): ...
class CompressionError(ClickHouseError): ...
class ConfigError(ClickHouseError): ...


class InsertStream:
    """Streaming INSERT session (sync)."""
    def send(self, block: Block) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> InsertStream: ...
    def __exit__(self, *args: Any) -> None: ...


class AsyncInsertStream:
    """Streaming INSERT session (async)."""
    async def send(self, block: Block, timeout: Optional[float] = None) -> None: ...
    async def close(self) -> None: ...
    async def __aenter__(self) -> AsyncInsertStream: ...
    async def __aexit__(self, *args: Any) -> None: ...


# ══════════════════════════════════════════════════════════════════════════
# Client (sync)
# ══════════════════════════════════════════════════════════════════════════

class Client:
    def __init__(
        self,
        addr: str,
        *,
        user: str = ...,
        password: str = ...,
        database: str = ...,
        settings: Optional[Dict[str, str]] = ...,
        compression: Optional[str] = ...,
        connect_timeout: float = ...,
        query_timeout: float = ...,
        max_response_size: int = ...,
        ssh_signer: Optional[Callable[[bytes], str]] = ...,
        validate_schema: bool = ...,
    ) -> None: ...
    def execute(self, query: str, params: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> None: ...
    def query(self, query: str, params: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> List[Dict[str, Any]]: ...
    def query_tuples(self, query: str, params: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> List[Tuple[Any, ...]]: ...
    def query_columns(self, query: str, params: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> Dict[str, List[Any]]: ...
    def query_blocks(self, query: str, params: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> List[Block]: ...
    def query_stream(self, query: str) -> Iterator[Block]: ...
    def insert(self, query: str, rows: List[Dict[str, Any]]) -> None: ...
    def insert_blocks(self, query: str, table_name: str, blocks: List[Block]) -> None: ...
    def insert_stream(self, query: str, table_name: str = ...) -> InsertStream: ...
    def ping(self) -> bool: ...
    def cancel(self) -> None: ...
    def server_info(self) -> Dict[str, Any]: ...
    def schema_for_table(self, table: str) -> Dict[str, Any]: ...
    def refresh_schema_for_table(self, table: str) -> Dict[str, Any]: ...
    def clear_schema_cache(self) -> None: ...
    def set_setting(self, name: str, value: str) -> None: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def __enter__(self) -> Client: ...
    def __exit__(self, *args: Any) -> None: ...


# ══════════════════════════════════════════════════════════════════════════
# AsyncClient — connection pool + asyncio bridge
# ══════════════════════════════════════════════════════════════════════════

class AsyncClient:
    def __init__(
        self,
        addr: str,
        *,
        user: str = ...,
        password: str = ...,
        database: str = ...,
        settings: Optional[Dict[str, str]] = ...,
        compression: Optional[str] = ...,
        connect_timeout: float = ...,
        query_timeout: float = ...,
        max_response_size: int = ...,
        pool_min_size: int = ...,
        pool_max_size: int = ...,
        pool_acquire_timeout: float = ...,
        pool_health_check_interval: float = ...,
        pool_max_idle_time: float = ...,
        pool_reaper_interval: float = ...,
        ssh_signer: Optional[Callable[[bytes], str]] = ...,
        validate_schema: bool = ...,
    ) -> None: ...
    async def execute(self, query: str, params: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> None: ...
    async def query(self, query: str, params: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> List[Dict[str, Any]]: ...
    async def query_tuples(self, query: str, params: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> List[Tuple[Any, ...]]: ...
    async def query_columns(self, query: str, params: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> Dict[str, List[Any]]: ...
    async def query_blocks(self, query: str, params: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> List[Block]: ...
    def query_stream(self, query: str) -> AsyncIterator[Block]: ...
    async def insert(self, query: str, rows: List[Dict[str, Any]]) -> None: ...
    async def insert_blocks(self, query: str, table_name: str, blocks: List[Block]) -> None: ...
    async def insert_stream(self, query: str, table_name: str = ...) -> AsyncInsertStream: ...
    async def ping(self) -> bool: ...
    async def cancel(self) -> None: ...
    def session(self) -> AsyncSession: ...
    async def server_info(self) -> Dict[str, Any]: ...
    async def schema_for_table(self, table: str) -> Dict[str, Any]: ...
    async def refresh_schema_for_table(self, table: str) -> Dict[str, Any]: ...
    async def clear_schema_cache(self) -> None: ...
    async def set_setting(self, name: str, value: str) -> None: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    async def __aenter__(self) -> AsyncClient: ...
    async def __aexit__(self, *args: Any) -> None: ...


class AsyncSession:
    async def execute(self, query: str, params: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> None: ...
    async def query(self, query: str, params: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> List[Dict[str, Any]]: ...
    async def query_blocks(self, query: str, params: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> List[Block]: ...
    async def ping(self) -> bool: ...
    async def cancel(self) -> None: ...
    async def set_setting(self, name: str, value: str) -> None: ...
    async def close(self) -> None: ...
    async def __aenter__(self) -> AsyncSession: ...
    async def __aexit__(self, *args: Any) -> None: ...


# ══════════════════════════════════════════════════════════════════════════
# Connection helpers
# ══════════════════════════════════════════════════════════════════════════

def connect(
    addr: str,
    *,
    user: str = ...,
    password: str = ...,
    database: str = ...,
    settings: Optional[Dict[str, str]] = ...,
    compression: Optional[str] = ...,
    connect_timeout: float = ...,
    query_timeout: float = ...,
    max_response_size: int = ...,
) -> Client: ...

def connect_async(
    addr: str,
    *,
    user: str = ...,
    password: str = ...,
    database: str = ...,
    settings: Optional[Dict[str, str]] = ...,
    compression: Optional[str] = ...,
    connect_timeout: float = ...,
    query_timeout: float = ...,
    max_response_size: int = ...,
    pool_min_size: int = ...,
    pool_max_size: int = ...,
    pool_acquire_timeout: float = ...,
    pool_health_check_interval: float = ...,
    pool_max_idle_time: float = ...,
    pool_reaper_interval: float = ...,
) -> AsyncClient: ...

def blocks_to_dicts(blocks: List[Block]) -> List[Dict[str, Any]]: ...
def dicts_to_block(rows: List[Dict[str, Any]], columns: List[tuple[str, str]]) -> Block: ...
