// ClickHouse native protocol revision gates.
//
// Servers are backward compatible with older client revisions. The client
// defaults to the latest known 26.x revision while negotiating the highest
// transport and serialization behavior supported by both peers.

pub const DBMS_MIN_REVISION_WITH_CLIENT_INFO: u64 = 54032;
pub const DBMS_MIN_REVISION_WITH_SERVER_TIMEZONE: u64 = 54058;
pub const DBMS_MIN_REVISION_WITH_QUOTA_KEY_IN_CLIENT_INFO: u64 = 54060;
pub const DBMS_MIN_REVISION_WITH_SERVER_DISPLAY_NAME: u64 = 54372;
pub const DBMS_MIN_REVISION_WITH_VERSION_PATCH: u64 = 54401;
pub const DBMS_MIN_REVISION_WITH_CLIENT_WRITE_INFO: u64 = 54420;
pub const DBMS_MIN_REVISION_WITH_SETTINGS_SERIALIZED_AS_STRINGS: u64 = 54429;
pub const DBMS_MIN_REVISION_WITH_INTERSERVER_SECRET: u64 = 54441;
pub const DBMS_MIN_REVISION_WITH_OPENTELEMETRY: u64 = 54442;
pub const DBMS_MIN_REVISION_WITH_DISTRIBUTED_DEPTH: u64 = 54448;
pub const DBMS_MIN_REVISION_WITH_INITIAL_QUERY_START_TIME: u64 = 54449;
pub const DBMS_MIN_REVISION_WITH_PARALLEL_REPLICAS: u64 = 54453;
pub const DBMS_MIN_PROTOCOL_VERSION_WITH_ADDENDUM: u64 = 54458;
pub const DBMS_MIN_PROTOCOL_VERSION_WITH_PARAMETERS: u64 = 54459;
pub const DBMS_MIN_PROTOCOL_VERSION_WITH_SERVER_QUERY_TIME_IN_PROGRESS: u64 = 54460;
pub const DBMS_MIN_PROTOCOL_VERSION_WITH_PASSWORD_COMPLEXITY_RULES: u64 = 54461;
pub const DBMS_MIN_REVISION_WITH_INTERSERVER_SECRET_V2: u64 = 54462;
pub const DBMS_MIN_PROTOCOL_VERSION_WITH_TOTAL_BYTES_IN_PROGRESS: u64 = 54463;
pub const DBMS_MIN_PROTOCOL_VERSION_WITH_TIMEZONE_UPDATES: u64 = 54464;
pub const DBMS_MIN_REVISION_WITH_SPARSE_SERIALIZATION: u64 = 54465;
pub const DBMS_MIN_REVISION_WITH_SSH_AUTHENTICATION: u64 = 54466;
pub const DBMS_MIN_REVISION_WITH_TABLES_STATUS: u64 = 54226;
pub const DBMS_MIN_REVISION_WITH_TABLE_READ_ONLY_CHECK: u64 = 54467;
pub const DBMS_MIN_REVISION_WITH_ROWS_BEFORE_AGGREGATION: u64 = 54469;
pub const DBMS_MIN_PROTOCOL_VERSION_WITH_CHUNKED_PACKETS: u64 = 54470;
pub const DBMS_MIN_REVISION_WITH_VERSIONED_PARALLEL_REPLICAS_PROTOCOL: u64 = 54471;
pub const DBMS_MIN_PROTOCOL_VERSION_WITH_INTERSERVER_EXTERNALLY_GRANTED_ROLES: u64 = 54472;
pub const DBMS_MIN_REVISION_WITH_V2_DYNAMIC_AND_JSON_SERIALIZATION: u64 = 54473;
pub const DBMS_MIN_REVISION_WITH_SERVER_SETTINGS: u64 = 54474;
pub const DBMS_MIN_REVISION_WITH_QUERY_AND_LINE_NUMBERS: u64 = 54475;
pub const DBMS_MIN_REVISION_WITH_JWT_IN_INTERSERVER: u64 = 54476;
pub const DBMS_MIN_REVISION_WITH_QUERY_PLAN_SERIALIZATION: u64 = 54477;
pub const DBMS_MIN_REVISION_WITH_PARALLEL_BLOCK_MARSHALLING: u64 = 54478;
pub const DBMS_MIN_REVISION_WITH_VERSIONED_CLUSTER_FUNCTION_PROTOCOL: u64 = 54479;
pub const DBMS_MIN_REVISION_WITH_OUT_OF_ORDER_BUCKETS_IN_AGGREGATION: u64 = 54480;
pub const DBMS_MIN_REVISION_WITH_COMPRESSED_LOGS_PROFILE_EVENTS_COLUMNS: u64 = 54481;
pub const DBMS_MIN_REVISION_WITH_REPLICATED_SERIALIZATION: u64 = 54482;
pub const DBMS_MIN_REVISION_WITH_NULLABLE_SPARSE_SERIALIZATION: u64 = 54483;
pub const DBMS_PARALLEL_REPLICAS_PROTOCOL_VERSION: u64 = 7;
pub const DBMS_CLUSTER_PROCESSING_PROTOCOL_VERSION: u64 = 6;

/// Latest known ClickHouse 26.x native TCP protocol revision.
pub const DEFAULT_PROTOCOL_REVISION: u64 = DBMS_MIN_REVISION_WITH_NULLABLE_SPARSE_SERIALIZATION;

/// Lowest revision this client intentionally tests. Older revisions need
/// binary setting serialization and different block headers.
pub const MIN_SUPPORTED_PROTOCOL_REVISION: u64 = DBMS_MIN_PROTOCOL_VERSION_WITH_PARAMETERS;

/// Highest opt-in revision for the current protocol implementation.
pub const MAX_SUPPORTED_PROTOCOL_REVISION: u64 =
    DBMS_MIN_REVISION_WITH_NULLABLE_SPARSE_SERIALIZATION;

pub fn effective_revision(client_revision: u64, server_revision: u64) -> u64 {
    client_revision.min(server_revision)
}

pub fn validate_supported_revision(revision: u64) -> Result<(), String> {
    if revision < MIN_SUPPORTED_PROTOCOL_REVISION {
        return Err(format!(
            "protocol revision {revision} is below the supported minimum \
             {MIN_SUPPORTED_PROTOCOL_REVISION}"
        ));
    }
    if revision > MAX_SUPPORTED_PROTOCOL_REVISION {
        return Err(format!(
            "protocol revision {revision} is not enabled; max supported is \
             {MAX_SUPPORTED_PROTOCOL_REVISION}"
        ));
    }
    Ok(())
}
